# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "wnono.com"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: wesley@wnono.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Wesley Chow'
author: 'Wesley Chow'
author_image: "/assets/images/author_me.jpg"

paginate:	5

url: "http://wnono.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/wesley_zhou
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/wezchow
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon: linkedin-alt
    url: https://www.linkedin.com/in/wezchow
    desc: Get connect on Linkedin

#  - icon: googleplus-alt
#   url:  https://google.com/+IanCamporezBrunelli
#    desc: Add me on google+

  - icon: feed
    url:  http://wnono.com/atom.xml
    desc: Subscribe to my feed

menu:
  - title:  Home | 主页
    url:  /

  - title:  About | 关于
    url:  /about

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
